In [1]:
from datetime import datetime, timedelta, date
import requests
import pandas as pd
import pickle
import numpy as np
import holidays

csv_te_voorspellen = './data csv/TEST_kijkcijfers.csv'

In [2]:
def ophalenKijkcijferData(startDate, endDate):
  print(f"Ophalen kijkcijfer-data van {startDate.year}-{startDate.month}-{startDate.day} tot {endDate.year}-{endDate.month}-{endDate.day}")
  kijkcijfersData = []
  #elke dag ophalen (startDate is huidige dag)
  while startDate <= endDate:
    datum = f"{startDate.year}-{startDate.month}-{startDate.day}"
    url = f"https://api.cim.be/api/cim_tv_public_results_daily_views?dateDiff={datum}&reportType=north"

    try:
      response = requests.get(url)
      if response.status_code == 200:
        data = response.json()
        programmaLijst = data.get('hydra:member', [])
                        
        for programma in programmaLijst:
          try:
            kijkcijfersData.append({
              'dateDiff': programma.get('dateDiff'),
              'ranking': programma.get('ranking'),
              'description': programma.get('description'),
              'channel': programma.get('channel'),
              'startTime': programma.get('startTime'),
              'rLength': programma.get('rLength'),
              'rateInK': programma.get('rateInK'),
              'live': programma.get('live')
            })
                                   
          except Exception as e:
            print(f"error {datum}: {e}")         
      else:
        print(f"no data {datum}")
                        
    except Exception as e:
      print(f"error: {e}")
    
    startDate += timedelta(days=1)

  print("KijkcijferData opgehaald")
  df = pd.DataFrame(kijkcijfersData)

  return df

def ophalenWeerData(startDate, endDate):
    latitude = 51.05
    longitude = 3.7167
    today = datetime.today().date()

    hourly_vars = [
        "temperature_2m", "apparent_temperature", "weather_code", "precipitation",
        "rain", "snowfall", "cloud_cover", "windspeed_10m", "sunshine_duration"
    ]
    
    common_params = {
        "latitude": latitude,
        "longitude": longitude,
        "hourly": hourly_vars,
        "timezone": "Europe/Brussels",
        "temperature_unit": "celsius",
        "precipitation_unit": "mm",
        "windspeed_unit": "kmh"
    }

    def fetch_weather_data(api_url, start, end):
        params = common_params.copy()
        params.update({
            "start_date": start.strftime('%Y-%m-%d'),
            "end_date": end.strftime('%Y-%m-%d')
        })
        response = requests.get(api_url, params=params)
        if response.status_code == 200:
            data = response.json().get("hourly", {})
            df = pd.DataFrame({var: data.get(var, []) for var in hourly_vars})
            df["timestamp"] = pd.to_datetime(data.get("time", []))
            if not df.empty:
                df["hour"] = df["timestamp"].dt.hour
                df["day_of_week"] = df["timestamp"].dt.dayofweek
                df["month"] = df["timestamp"].dt.month
                df["year"] = df["timestamp"].dt.year
            return df
        else:
            print(f"Fout bij ophalen data: {response.status_code}")
            print(response.text)
            return pd.DataFrame()

    dataframes = []

    # Historische data
    if startDate.date() < today:
        print("Ophalen historische data")
        hist_end = min(endDate.date(), today - timedelta(days=1))
        dataframes.append(fetch_weather_data(
            "https://archive-api.open-meteo.com/v1/archive",
            startDate, datetime.combine(hist_end, datetime.min.time())
        ))

    # Forecast data
    if endDate.date() >= today:
        print("Ophalen forecast data")
        forecast_start = max(endDate, datetime.combine(today, datetime.min.time()))
        print(forecast_start)
        dataframes.append(fetch_weather_data(
            "https://api.open-meteo.com/v1/forecast",
            forecast_start, endDate
        ))

    if dataframes:
        print("Weerdata opgehaald")
        return pd.concat(dataframes).sort_values("timestamp").reset_index(drop=True)
    else:
        return pd.DataFrame()

In [3]:
def testCSV(csv):
    df = pd.read_csv(csv, delimiter=';')
    # Kolommen hernoemen
    df = df.rename(columns={
        'Programma': 'description',
        'Zender': 'channel',
        'Datum ': 'dateDiff',
        'Start ': 'startTime',
        'Duur': 'rLength'
    })
    # Datum en tijd samenvoegen tot datetime
    df['dateDiff'] = pd.to_datetime(df['dateDiff'], dayfirst=True)
    # Starttijd naar HH:MM:SS
    df['startTime'] = df['startTime'].str[:8]
    # Duur naar HH:MM:SS
    df['rLength'] = df['rLength'].apply(lambda x: str(pd.to_timedelta(x)))
    # Voeg dummy kolommen toe als nodig
    df['ranking'] = 0
    df['live'] = 0
    df['Kijkers'] = None

    return df[['dateDiff', 'ranking', 'description', 'channel', 'startTime', 'rLength', 'live']]

In [4]:
teVoorspellen = testCSV(csv_te_voorspellen)

teVoorspellen['dateDiff'] = pd.to_datetime(teVoorspellen['dateDiff'])

end_date = teVoorspellen['dateDiff'].max()
start_date = end_date - timedelta(weeks=3)
histKijkcijfers = ophalenKijkcijferData(start_date, end_date - timedelta(days=1))
histWeerdata = ophalenWeerData(start_date, end_date)

Ophalen kijkcijfer-data van 2025-4-15 tot 2025-5-5
KijkcijferData opgehaald
Ophalen historische data
Weerdata opgehaald

In [5]:
def cleanKijkcijferData(df):

    # Zet 'Kijkers' kolom, als 'rateInK' bestaat
    if 'rateInK' in df.columns:
        df['Kijkers'] = (
            df['rateInK']
            .dropna()
            .astype(str)
            .str.replace('.', '', regex=False)
            .astype(int)
        )
    else:
        df['Kijkers'] = None

    # rLength aanpassen
    df['rLength'] = df['rLength'].astype(str).apply(
    lambda x: x[-8:] if 'days' in x else x.zfill(8)
    )

    # Tijd aanpassen
    tijd_regex = r'^\d{2}:\d{2}:\d{2}$'
    # Omzetten naar datetime
    df['date'] = pd.to_datetime(df['dateDiff']).dt.date
    # Filter rijen met formaat
    df = df[df['startTime'].str.match(tijd_regex, na=False) & df['rLength'].str.match(tijd_regex, na=False)].copy()
    
    # Afleveringlengte naar seconden omzetten 
    df['Lengte_sec'] = pd.to_timedelta(df['rLength']).dt.total_seconds().astype(int)

    # Uren met 24+
    def time_cor(rij):
        tijdArr = rij['startTime'].split(':')
        if int(tijdArr[0]) >= 24:
            tijdArr[0] = str(int(tijdArr[0]) - 24).zfill(2)
            rij['date'] += timedelta(days=1)
        rij['startTime'] = ':'.join(tijdArr)
        return rij
    
    df = df.apply(time_cor, axis=1)

    # 1 kolom voor beide data
    df['FullDate'] = pd.to_datetime(df['date'].astype(str) 
                                    + " " + df['startTime'].astype(str))
    
    # Hour en minute voor join later on
    df['hour'] = pd.to_datetime(df['startTime'], format='%H:%M:%S').dt.hour
    df['minute'] = 0

    # Kolommen verwijderen die niet nodig meer zijn, als ze bestaan
    columns_to_drop = ['startTime', 'rLength', 'rateInK', 'ranking', 'live']
    df.drop([col for col in columns_to_drop if col in df.columns], axis=1, inplace=True)


    # De nieuwe dataframe
    df = df[['FullDate', 'date', 'hour', 'minute', 'channel', 'description', 'Lengte_sec', 'Kijkers']]

    # Hernoemen kolommen
    df.rename(columns={'description': 'Programma', 'channel': 'Kanaal'}, inplace=True)

    return df


def cleanWeerData(df):
  weerData = df
  weerData['timestamp'] = pd.to_datetime(weerData['timestamp'])
  #naar zelfde formaat als kijkcijfer datum
  weerData['datetime'] = weerData['timestamp'].dt.strftime('%Y-%m-%d %H:%M:%S')

  #hour voor join later on
  weerData['hour'] = pd.to_datetime(weerData['datetime']).dt.hour
  weerData['minute'] = pd.to_datetime(weerData['datetime']).dt.minute
  weerData['date'] = pd.to_datetime(weerData['datetime']).dt.date

  #verwijder kolom
  weerData = weerData.drop(columns=['timestamp'])

  weerData = weerData[['datetime', 'date' ,'hour', 'minute', 'temperature_2m', 'apparent_temperature', 
                            'rain', 'snowfall', 'weather_code', 'cloud_cover', 
                            'windspeed_10m', 'sunshine_duration']]

  #hernoemen kolommen
  weerData.rename(columns={'temperature_2m':'Temperatuur', 'apparent_temperature':'Gevoelstemp', 'windspeed_10m': 'Windsnelheid', 'rain':'Regen', 'snowfall': 'Sneeuw', 'weather_code':'Weercode', 'cloud_cover':'Bewolking', 'sunshine_duration':'Zonnenschijn'}, inplace=True)

  return weerData

In [56]:
histWeerdataClean = cleanWeerData(histWeerdata)
histKijkcijfersClean = cleanKijkcijferData(histKijkcijfers)
teVoorspellenClean = cleanKijkcijferData(teVoorspellen)
print(histWeerdataClean)
print(histKijkcijfersClean)
print(teVoorspellenClean)

                datetime        date  hour  minute  Temperatuur  Gevoelstemp  \
0    2025-04-15 00:00:00  2025-04-15     0       0         12.3         10.0
1    2025-04-15 01:00:00  2025-04-15     1       0         11.6          9.4
2    2025-04-15 02:00:00  2025-04-15     2       0         11.1          8.8
3    2025-04-15 03:00:00  2025-04-15     3       0         10.8          8.1
4    2025-04-15 04:00:00  2025-04-15     4       0         10.7          8.1
5    2025-04-15 05:00:00  2025-04-15     5       0         10.9          8.3
6    2025-04-15 06:00:00  2025-04-15     6       0         11.2          8.5
7    2025-04-15 07:00:00  2025-04-15     7       0         11.0          8.5
8    2025-04-15 08:00:00  2025-04-15     8       0         11.3          9.4
9    2025-04-15 09:00:00  2025-04-15     9       0         13.0         11.4
10   2025-04-15 10:00:00  2025-04-15    10       0         15.1         13.6
11   2025-04-15 11:00:00  2025-04-15    11       0         16.2         14.2
12   2025-04-15 12:00:00  2025-04-15    12       0         16.4         14.4
13   2025-04-15 13:00:00  2025-04-15    13       0         16.8         15.2
14   2025-04-15 14:00:00  2025-04-15    14       0         17.1         15.3
15   2025-04-15 15:00:00  2025-04-15    15       0         17.0         15.5
16   2025-04-15 16:00:00  2025-04-15    16       0         17.2         15.4
17   2025-04-15 17:00:00  2025-04-15    17       0         17.7         16.2
18   2025-04-15 18:00:00  2025-04-15    18       0         18.3         16.7
19   2025-04-15 19:00:00  2025-04-15    19       0         18.0         16.2
20   2025-04-15 20:00:00  2025-04-15    20       0         16.6         14.5
21   2025-04-15 21:00:00  2025-04-15    21       0         14.9         13.0
22   2025-04-15 22:00:00  2025-04-15    22       0         13.8         11.9
23   2025-04-15 23:00:00  2025-04-15    23       0         13.3         11.3
24   2025-04-16 00:00:00  2025-04-16     0       0         12.8         10.7
25   2025-04-16 01:00:00  2025-04-16     1       0         12.0          9.9
26   2025-04-16 02:00:00  2025-04-16     2       0         11.2          9.0
27   2025-04-16 03:00:00  2025-04-16     3       0         10.3          7.9
28   2025-04-16 04:00:00  2025-04-16     4       0          9.4          6.6
29   2025-04-16 05:00:00  2025-04-16     5       0          8.9          5.9
30   2025-04-16 06:00:00  2025-04-16     6       0          8.8          5.9
31   2025-04-16 07:00:00  2025-04-16     7       0          8.7          6.0
32   2025-04-16 08:00:00  2025-04-16     8       0          8.9          6.0
33   2025-04-16 09:00:00  2025-04-16     9       0          9.1          6.1
34   2025-04-16 10:00:00  2025-04-16    10       0          9.5          6.0
35   2025-04-16 11:00:00  2025-04-16    11       0         10.0          6.6
36   2025-04-16 12:00:00  2025-04-16    12       0         10.7          7.6
37   2025-04-16 13:00:00  2025-04-16    13       0         11.4          8.4
38   2025-04-16 14:00:00  2025-04-16    14       0         12.1          9.2
39   2025-04-16 15:00:00  2025-04-16    15       0         12.2          8.8
40   2025-04-16 16:00:00  2025-04-16    16       0         12.5          9.3
41   2025-04-16 17:00:00  2025-04-16    17       0         13.3          9.8
42   2025-04-16 18:00:00  2025-04-16    18       0         13.1         10.0
43   2025-04-16 19:00:00  2025-04-16    19       0         12.8         10.5
44   2025-04-16 20:00:00  2025-04-16    20       0         12.1         10.9
45   2025-04-16 21:00:00  2025-04-16    21       0         11.1          9.3
46   2025-04-16 22:00:00  2025-04-16    22       0         10.4          8.7
47   2025-04-16 23:00:00  2025-04-16    23       0          9.9          8.3
48   2025-04-17 00:00:00  2025-04-17     0       0          9.5          7.9
49   2025-04-17 01:00:00  2025-04-17     1       0          9.1          7.3
50   2025-04-17 02:00:00  2025-04-17     2       0          8.7          6.9
51   2025-04-17 03:00:00  2025-04-17     3       0          8.1          6.2
52   2025-04-17 04:00:00  2025-04-17     4       0          7.9          6.0
53   2025-04-17 05:00:00  2025-04-17     5       0          7.7          5.9
54   2025-04-17 06:00:00  2025-04-17     6       0          7.4          5.7
55   2025-04-17 07:00:00  2025-04-17     7       0          6.9          5.1
56   2025-04-17 08:00:00  2025-04-17     8       0          7.7          6.1
57   2025-04-17 09:00:00  2025-04-17     9       0          9.5          8.2
58   2025-04-17 10:00:00  2025-04-17    10       0         11.3          9.5
59   2025-04-17 11:00:00  2025-04-17    11       0         12.4         10.3
60   2025-04-17 12:00:00  2025-04-17    12       0         12.8         10.7
61   2025-04-17 13:00:00  2025-04-17    13       0         13.5         11.3
62   2025-04-17 14:00:00  2025-04-17    14       0         14.4         12.2
63   2025-04-17 15:00:00  2025-04-17    15       0         14.4         11.4
64   2025-04-17 16:00:00  2025-04-17    16       0         13.9         11.0
65   2025-04-17 17:00:00  2025-04-17    17       0         13.6         10.9
66   2025-04-17 18:00:00  2025-04-17    18       0         13.2         10.7
67   2025-04-17 19:00:00  2025-04-17    19       0         12.6         10.6
68   2025-04-17 20:00:00  2025-04-17    20       0         11.8         10.6
69   2025-04-17 21:00:00  2025-04-17    21       0         10.8          9.6
70   2025-04-17 22:00:00  2025-04-17    22       0          9.9          8.7
71   2025-04-17 23:00:00  2025-04-17    23       0          9.2          7.9
72   2025-04-18 00:00:00  2025-04-18     0       0          8.9          7.4
73   2025-04-18 01:00:00  2025-04-18     1       0          8.4          6.8
74   2025-04-18 02:00:00  2025-04-18     2       0          7.8          5.9
75   2025-04-18 03:00:00  2025-04-18     3       0          7.0          4.9
76   2025-04-18 04:00:00  2025-04-18     4       0          6.7          4.4
77   2025-04-18 05:00:00  2025-04-18     5       0          6.6          4.3
78   2025-04-18 06:00:00  2025-04-18     6       0          6.4          4.2
79   2025-04-18 07:00:00  2025-04-18     7       0          6.0          4.2
80   2025-04-18 08:00:00  2025-04-18     8       0          6.6          4.7
81   2025-04-18 09:00:00  2025-04-18     9       0          7.9          6.2
82   2025-04-18 10:00:00  2025-04-18    10       0          9.5          8.1
83   2025-04-18 11:00:00  2025-04-18    11       0         11.5         10.2
84   2025-04-18 12:00:00  2025-04-18    12       0         13.4         12.4
85   2025-04-18 13:00:00  2025-04-18    13       0         14.7         13.7
86   2025-04-18 14:00:00  2025-04-18    14       0         15.4         14.3
87   2025-04-18 15:00:00  2025-04-18    15       0         16.0         14.7
88   2025-04-18 16:00:00  2025-04-18    16       0         16.4         14.9
89   2025-04-18 17:00:00  2025-04-18    17       0         16.5         14.1
90   2025-04-18 18:00:00  2025-04-18    18       0         16.2         13.3
91   2025-04-18 19:00:00  2025-04-18    19       0         15.5         12.5
92   2025-04-18 20:00:00  2025-04-18    20       0         14.5         11.9
93   2025-04-18 21:00:00  2025-04-18    21       0         13.4         10.6
94   2025-04-18 22:00:00  2025-04-18    22       0         12.0          9.0
95   2025-04-18 23:00:00  2025-04-18    23       0         10.9          7.8
96   2025-04-19 00:00:00  2025-04-19     0       0         10.0          6.9
97   2025-04-19 01:00:00  2025-04-19     1       0          9.2          6.2
98   2025-04-19 02:00:00  2025-04-19     2       0          8.5          5.6
99   2025-04-19 03:00:00  2025-04-19     3       0          8.3          5.4
100  2025-04-19 04:00:00  2025-04-19     4       0          7.9          5.0
101  2025-04-19 05:00:00  2025-04-19     5       0          7.5          4.5
102  2025-04-19 06:00:00  2025-04-19     6       0          7.1          4.1
103  2025-04-19 07:00:00  2025-04-19     7       0          7.0          3.9
104  2025-04-19 08:00:00  2025-04-19     8       0          7.6          4.6
105  2025-04-19 09:00:00  2025-04-19     9       0          8.8          6.3
106  2025-04-19 10:00:00  2025-04-19    10       0         10.4          8.0
107  2025-04-19 11:00:00  2025-04-19    11       0         12.5          9.5
108  2025-04-19 12:00:00  2025-04-19    12       0         14.0         11.1
109  2025-04-19 13:00:00  2025-04-19    13       0         15.1         12.7
110  2025-04-19 14:00:00  2025-04-19    14       0         16.5         14.2
111  2025-04-19 15:00:00  2025-04-19    15       0         17.0         14.4
112  2025-04-19 16:00:00  2025-04-19    16       0         17.3         14.4
113  2025-04-19 17:00:00  2025-04-19    17       0         17.4         14.0
114  2025-04-19 18:00:00  2025-04-19    18       0         17.3         13.9
115  2025-04-19 19:00:00  2025-04-19    19       0         16.7         13.2
116  2025-04-19 20:00:00  2025-04-19    20       0         15.4         12.2
117  2025-04-19 21:00:00  2025-04-19    21       0         13.9         10.4
118  2025-04-19 22:00:00  2025-04-19    22       0         13.1          9.4
119  2025-04-19 23:00:00  2025-04-19    23       0         12.3          8.9
120  2025-04-20 00:00:00  2025-04-20     0       0         11.3          8.2
121  2025-04-20 01:00:00  2025-04-20     1       0         10.1          7.0
122  2025-04-20 02:00:00  2025-04-20     2       0          9.2          6.2
123  2025-04-20 03:00:00  2025-04-20     3       0          8.4          5.4
124  2025-04-20 04:00:00  2025-04-20     4       0          7.8          4.8
125  2025-04-20 05:00:00  2025-04-20     5       0          7.2          4.3
126  2025-04-20 06:00:00  2025-04-20     6       0          6.8          3.8
127  2025-04-20 07:00:00  2025-04-20     7       0          6.5          3.5
128  2025-04-20 08:00:00  2025-04-20     8       0          7.1          4.3
129  2025-04-20 09:00:00  2025-04-20     9       0          8.3          5.6
130  2025-04-20 10:00:00  2025-04-20    10       0         10.4          7.6
131  2025-04-20 11:00:00  2025-04-20    11       0         12.8         10.4
132  2025-04-20 12:00:00  2025-04-20    12       0         12.9         11.7
133  2025-04-20 13:00:00  2025-04-20    13       0         13.6         12.1
134  2025-04-20 14:00:00  2025-04-20    14       0         14.7         13.4
135  2025-04-20 15:00:00  2025-04-20    15       0         15.6         14.7
136  2025-04-20 16:00:00  2025-04-20    16       0         16.4         15.2
137  2025-04-20 17:00:00  2025-04-20    17       0         16.0         14.9
138  2025-04-20 18:00:00  2025-04-20    18       0         15.7         14.8
139  2025-04-20 19:00:00  2025-04-20    19       0         14.8         14.5
140  2025-04-20 20:00:00  2025-04-20    20       0         13.8         13.2
141  2025-04-20 21:00:00  2025-04-20    21       0         12.7         12.3
142  2025-04-20 22:00:00  2025-04-20    22       0         11.7         10.7
143  2025-04-20 23:00:00  2025-04-20    23       0         10.9          9.8
144  2025-04-21 00:00:00  2025-04-21     0       0         10.4          9.5
145  2025-04-21 01:00:00  2025-04-21     1       0         10.0          9.3
146  2025-04-21 02:00:00  2025-04-21     2       0          9.9          9.0
147  2025-04-21 03:00:00  2025-04-21     3       0          8.9          7.9
148  2025-04-21 04:00:00  2025-04-21     4       0          9.3          8.0
149  2025-04-21 05:00:00  2025-04-21     5       0          9.0          7.7
150  2025-04-21 06:00:00  2025-04-21     6       0          8.2          6.9
151  2025-04-21 07:00:00  2025-04-21     7       0          7.8          6.2
152  2025-04-21 08:00:00  2025-04-21     8       0          8.3          6.7
153  2025-04-21 09:00:00  2025-04-21     9       0          9.9          9.0
154  2025-04-21 10:00:00  2025-04-21    10       0         11.8         10.8
155  2025-04-21 11:00:00  2025-04-21    11       0         13.1         12.3
156  2025-04-21 12:00:00  2025-04-21    12       0         14.0         13.2
157  2025-04-21 13:00:00  2025-04-21    13       0         14.5         13.7
158  2025-04-21 14:00:00  2025-04-21    14       0         15.3         14.4
159  2025-04-21 15:00:00  2025-04-21    15       0         16.1         14.9
160  2025-04-21 16:00:00  2025-04-21    16       0         16.2         15.0
161  2025-04-21 17:00:00  2025-04-21    17       0         13.8         12.1
162  2025-04-21 18:00:00  2025-04-21    18       0         13.4         13.4
163  2025-04-21 19:00:00  2025-04-21    19       0         13.4         12.9
164  2025-04-21 20:00:00  2025-04-21    20       0         12.9         12.5
165  2025-04-21 21:00:00  2025-04-21    21       0         12.2         11.6
166  2025-04-21 22:00:00  2025-04-21    22       0         11.7         11.2
167  2025-04-21 23:00:00  2025-04-21    23       0         11.2         10.0
168  2025-04-22 00:00:00  2025-04-22     0       0         11.0          9.4
169  2025-04-22 01:00:00  2025-04-22     1       0         10.1          8.2
170  2025-04-22 02:00:00  2025-04-22     2       0          9.4          7.4
171  2025-04-22 03:00:00  2025-04-22     3       0          9.5          7.6
172  2025-04-22 04:00:00  2025-04-22     4       0          9.0          6.9
173  2025-04-22 05:00:00  2025-04-22     5       0          8.5          6.4
174  2025-04-22 06:00:00  2025-04-22     6       0          8.1          6.0
175  2025-04-22 07:00:00  2025-04-22     7       0          7.7          5.7
176  2025-04-22 08:00:00  2025-04-22     8       0          8.5          6.5
177  2025-04-22 09:00:00  2025-04-22     9       0          9.8          7.8
178  2025-04-22 10:00:00  2025-04-22    10       0         11.3          9.4
179  2025-04-22 11:00:00  2025-04-22    11       0         12.5         10.6
180  2025-04-22 12:00:00  2025-04-22    12       0         13.9         12.0
181  2025-04-22 13:00:00  2025-04-22    13       0         15.0         13.5
182  2025-04-22 14:00:00  2025-04-22    14       0         15.5         13.3
183  2025-04-22 15:00:00  2025-04-22    15       0         15.8         13.4
184  2025-04-22 16:00:00  2025-04-22    16       0         16.1         13.5
185  2025-04-22 17:00:00  2025-04-22    17       0         16.2         13.5
186  2025-04-22 18:00:00  2025-04-22    18       0         15.3         13.1
187  2025-04-22 19:00:00  2025-04-22    19       0         14.0         12.2
188  2025-04-22 20:00:00  2025-04-22    20       0         13.0         11.8
189  2025-04-22 21:00:00  2025-04-22    21       0         11.6         11.1
190  2025-04-22 22:00:00  2025-04-22    22       0         10.9         10.2
191  2025-04-22 23:00:00  2025-04-22    23       0         10.9         10.3
192  2025-04-23 00:00:00  2025-04-23     0       0         10.5          9.8
193  2025-04-23 01:00:00  2025-04-23     1       0          9.9          8.9
194  2025-04-23 02:00:00  2025-04-23     2       0          9.9          8.8
195  2025-04-23 03:00:00  2025-04-23     3       0          8.7          7.4
196  2025-04-23 04:00:00  2025-04-23     4       0          8.2          6.5
197  2025-04-23 05:00:00  2025-04-23     5       0          8.2          6.0
198  2025-04-23 06:00:00  2025-04-23     6       0          8.3          6.0
199  2025-04-23 07:00:00  2025-04-23     7       0          8.4          6.0
200  2025-04-23 08:00:00  2025-04-23     8       0          9.5          7.0
201  2025-04-23 09:00:00  2025-04-23     9       0         10.6          8.4
202  2025-04-23 10:00:00  2025-04-23    10       0         10.6          8.9
203  2025-04-23 11:00:00  2025-04-23    11       0         11.5         10.2
204  2025-04-23 12:00:00  2025-04-23    12       0         10.9          9.1
205  2025-04-23 13:00:00  2025-04-23    13       0         11.8         10.5
206  2025-04-23 14:00:00  2025-04-23    14       0         12.8         11.5
207  2025-04-23 15:00:00  2025-04-23    15       0         12.3          9.4
208  2025-04-23 16:00:00  2025-04-23    16       0         12.2          9.5
209  2025-04-23 17:00:00  2025-04-23    17       0         12.2          9.7
210  2025-04-23 18:00:00  2025-04-23    18       0         12.2         10.4
211  2025-04-23 19:00:00  2025-04-23    19       0         12.1         10.2
212  2025-04-23 20:00:00  2025-04-23    20       0         12.0         10.7
213  2025-04-23 21:00:00  2025-04-23    21       0         10.7          9.8
214  2025-04-23 22:00:00  2025-04-23    22       0          9.9          8.4
215  2025-04-23 23:00:00  2025-04-23    23       0          9.8          8.4
216  2025-04-24 00:00:00  2025-04-24     0       0          9.4          8.0
217  2025-04-24 01:00:00  2025-04-24     1       0          8.9          7.4
218  2025-04-24 02:00:00  2025-04-24     2       0          8.2          6.6
219  2025-04-24 03:00:00  2025-04-24     3       0          8.9          7.4
220  2025-04-24 04:00:00  2025-04-24     4       0          8.9          7.6
221  2025-04-24 05:00:00  2025-04-24     5       0          9.2          7.5
222  2025-04-24 06:00:00  2025-04-24     6       0          9.4          7.7
223  2025-04-24 07:00:00  2025-04-24     7       0          9.0          7.0
224  2025-04-24 08:00:00  2025-04-24     8       0          9.8          7.7
225  2025-04-24 09:00:00  2025-04-24     9       0         10.8          8.1
226  2025-04-24 10:00:00  2025-04-24    10       0         11.5          8.8
227  2025-04-24 11:00:00  2025-04-24    11       0         11.8          8.9
228  2025-04-24 12:00:00  2025-04-24    12       0         12.1          9.3
229  2025-04-24 13:00:00  2025-04-24    13       0         13.0          9.9
230  2025-04-24 14:00:00  2025-04-24    14       0         13.5         10.5
231  2025-04-24 15:00:00  2025-04-24    15       0         12.8          9.6
232  2025-04-24 16:00:00  2025-04-24    16       0         13.4         10.3
233  2025-04-24 17:00:00  2025-04-24    17       0         12.7          9.6
234  2025-04-24 18:00:00  2025-04-24    18       0         12.0          9.0
235  2025-04-24 19:00:00  2025-04-24    19       0         11.4          8.6
236  2025-04-24 20:00:00  2025-04-24    20       0         11.0          8.4
237  2025-04-24 21:00:00  2025-04-24    21       0         10.6          8.4
238  2025-04-24 22:00:00  2025-04-24    22       0         10.5          8.3
239  2025-04-24 23:00:00  2025-04-24    23       0         10.3          8.2
240  2025-04-25 00:00:00  2025-04-25     0       0         10.0          8.0
241  2025-04-25 01:00:00  2025-04-25     1       0         10.3          8.3
242  2025-04-25 02:00:00  2025-04-25     2       0         10.0          8.0
243  2025-04-25 03:00:00  2025-04-25     3       0         10.3          8.7
244  2025-04-25 04:00:00  2025-04-25     4       0         10.0          8.3
245  2025-04-25 05:00:00  2025-04-25     5       0          9.4          7.7
246  2025-04-25 06:00:00  2025-04-25     6       0          8.5          6.7
247  2025-04-25 07:00:00  2025-04-25     7       0          8.1          6.4
248  2025-04-25 08:00:00  2025-04-25     8       0          8.9          7.1
249  2025-04-25 09:00:00  2025-04-25     9       0         10.0          7.7
250  2025-04-25 10:00:00  2025-04-25    10       0         11.1          9.0
251  2025-04-25 11:00:00  2025-04-25    11       0         12.6         10.8
252  2025-04-25 12:00:00  2025-04-25    12       0         14.1         12.6
253  2025-04-25 13:00:00  2025-04-25    13       0         15.1         14.1
254  2025-04-25 14:00:00  2025-04-25    14       0         16.1         15.8
255  2025-04-25 15:00:00  2025-04-25    15       0         15.7         13.8
256  2025-04-25 16:00:00  2025-04-25    16       0         15.8         13.7
257  2025-04-25 17:00:00  2025-04-25    17       0         15.7         13.5

In [57]:
def mergen(kijkcijfers, weer):
  kijkcijfersWeer = pd.merge(kijkcijfers, weer, on=['date', 'hour'], how='left')
  kijkcijfersWeer = kijkcijfersWeer[['FullDate', 'date', 'hour', 'Kanaal', 'Programma', 'Lengte_sec', 'Kijkers', 'Temperatuur', 'Gevoelstemp', 'Regen', 'Sneeuw', 'Weercode', 'Bewolking', 'Windsnelheid', 'Zonnenschijn']]
  kijkcijfersWeer.dropna(inplace=True)
  return kijkcijfersWeer

In [58]:
histKijkcijfersWeer = mergen(histKijkcijfersClean, histWeerdataClean)
print(histKijkcijfersWeer)

               FullDate        date  hour                  Kanaal  \
0   2025-04-15 20:14:58  2025-04-15    20                   VRT 1
1   2025-04-15 20:41:25  2025-04-15    20                   VRT 1
2   2025-04-15 19:00:05  2025-04-15    19                   VRT 1
3   2025-04-15 21:27:50  2025-04-15    21                   VRT 1
4   2025-04-15 20:44:56  2025-04-15    20                     VTM
5   2025-04-15 19:45:34  2025-04-15    19                   VRT 1
6   2025-04-15 20:09:04  2025-04-15    20                     VTM
7   2025-04-15 18:59:48  2025-04-15    18                     VTM
8   2025-04-15 18:28:21  2025-04-15    18                   VRT 1
9   2025-04-15 21:19:26  2025-04-15    21                   PLAY4
10  2025-04-15 13:00:04  2025-04-15    13                   VRT 1
11  2025-04-15 18:24:52  2025-04-15    18                     VTM
12  2025-04-15 20:00:03  2025-04-15    20              VRT CANVAS
13  2025-04-15 22:02:15  2025-04-15    22                   VRT 1
14  2025-04-15 18:09:20  2025-04-15    18                   VRT 1
15  2025-04-15 21:00:54  2025-04-15    21                    VTM2
16  2025-04-15 19:59:03  2025-04-15    19                   PLAY4
17  2025-04-15 21:53:36  2025-04-15    21                     VTM
18  2025-04-15 12:59:48  2025-04-15    12                     VTM
19  2025-04-15 22:25:24  2025-04-15    22                   VRT 1
20  2025-04-16 21:20:50  2025-04-16    21                   VRT 1
21  2025-04-16 20:15:55  2025-04-16    20                   VRT 1
22  2025-04-16 19:00:04  2025-04-16    19                   VRT 1
23  2025-04-16 19:43:09  2025-04-16    19                   VRT 1
24  2025-04-16 20:07:56  2025-04-16    20                     VTM
25  2025-04-16 20:40:43  2025-04-16    20                   VRT 1
26  2025-04-16 18:30:05  2025-04-16    18                   VRT 1
27  2025-04-16 18:59:48  2025-04-16    18                     VTM
28  2025-04-16 21:21:59  2025-04-16    21                   PLAY4
29  2025-04-16 20:43:00  2025-04-16    20                     VTM
30  2025-04-16 21:02:43  2025-04-16    21                    VTM2
31  2025-04-16 13:00:04  2025-04-16    13                   VRT 1
32  2025-04-16 18:11:21  2025-04-16    18                   VRT 1
33  2025-04-16 18:25:47  2025-04-16    18                     VTM
34  2025-04-16 19:59:03  2025-04-16    19                   PLAY4
35  2025-04-16 15:30:39  2025-04-16    15                   VRT 1
36  2025-04-16 21:22:33  2025-04-16    21              VRT CANVAS
37  2025-04-16 12:59:48  2025-04-16    12                     VTM
38  2025-04-16 20:00:03  2025-04-16    20              VRT CANVAS
39  2025-04-16 21:56:46  2025-04-16    21                   VRT 1
40  2025-04-17 20:12:50  2025-04-17    20                   VRT 1
41  2025-04-17 21:34:48  2025-04-17    21                   VRT 1
42  2025-04-17 19:00:04  2025-04-17    19                   VRT 1
43  2025-04-17 20:06:43  2025-04-17    20                     VTM
44  2025-04-17 20:41:49  2025-04-17    20                     VTM
45  2025-04-17 19:42:01  2025-04-17    19                   VRT 1
46  2025-04-17 18:59:52  2025-04-17    18                     VTM
47  2025-04-17 18:30:00  2025-04-17    18                   VRT 1
48  2025-04-17 21:20:44  2025-04-17    21                   PLAY4
49  2025-04-17 21:32:21  2025-04-17    21                    VTM2
50  2025-04-17 20:42:06  2025-04-17    20                   VRT 1
51  2025-04-17 13:00:04  2025-04-17    13                   VRT 1
52  2025-04-17 22:10:39  2025-04-17    22                   VRT 1
53  2025-04-17 18:25:57  2025-04-17    18                     VTM
54  2025-04-17 20:00:03  2025-04-17    20              VRT CANVAS
55  2025-04-17 21:58:36  2025-04-17    21                     VTM
56  2025-04-17 19:59:03  2025-04-17    19                   PLAY4
57  2025-04-17 18:11:03  2025-04-17    18                   VRT 1
58  2025-04-17 12:59:48  2025-04-17    12                     VTM
59  2025-04-17 20:37:42  2025-04-17    20                    VTM2
60  2025-04-18 20:16:27  2025-04-18    20                   VRT 1
61  2025-04-18 19:00:04  2025-04-18    19                   VRT 1
62  2025-04-18 20:41:38  2025-04-18    20                     VTM
63  2025-04-18 20:07:47  2025-04-18    20                     VTM
64  2025-04-18 19:46:42  2025-04-18    19                   VRT 1
65  2025-04-18 18:29:30  2025-04-18    18                   VRT 1
66  2025-04-18 18:59:55  2025-04-18    18                     VTM
67  2025-04-18 15:00:33  2025-04-18    15                   VRT 1
68  2025-04-18 20:42:26  2025-04-18    20                   VRT 1
69  2025-04-18 13:00:04  2025-04-18    13                   VRT 1
70  2025-04-18 22:15:27  2025-04-18    22                   VRT 1
71  2025-04-18 21:33:18  2025-04-18    21              VRT CANVAS
72  2025-04-18 22:11:57  2025-04-18    22                     VTM
73  2025-04-18 18:12:00  2025-04-18    18                   VRT 1
74  2025-04-18 21:26:53  2025-04-18    21                   VRT 1
75  2025-04-18 20:40:03  2025-04-18    20                   PLAY4
76  2025-04-18 17:41:40  2025-04-18    17                   VRT 1
77  2025-04-18 12:59:48  2025-04-18    12                     VTM
78  2025-04-18 20:00:03  2025-04-18    20              VRT CANVAS
79  2025-04-18 20:37:45  2025-04-18    20                    VTM3
80  2025-04-19 19:00:05  2025-04-19    19                   VRT 1
81  2025-04-19 20:52:56  2025-04-19    20                   VRT 1
82  2025-04-19 20:19:21  2025-04-19    20                   VRT 1
83  2025-04-19 18:59:48  2025-04-19    18                     VTM
84  2025-04-19 21:25:08  2025-04-19    21                   VRT 1
85  2025-04-19 19:48:56  2025-04-19    19                   VRT 1
86  2025-04-19 19:54:56  2025-04-19    19                     VTM
87  2025-04-19 22:17:41  2025-04-19    22                   VRT 1
88  2025-04-19 13:00:04  2025-04-19    13                   VRT 1
89  2025-04-19 21:28:36  2025-04-19    21              VRT CANVAS
90  2025-04-19 20:30:08  2025-04-19    20                     VTM
91  2025-04-19 12:59:48  2025-04-19    12                     VTM
92  2025-04-19 22:43:07  2025-04-19    22                   VRT 1
93  2025-04-19 21:32:52  2025-04-19    21                     VTM
94  2025-04-19 18:11:59  2025-04-19    18                   VRT 1
95  2025-04-19 14:37:32  2025-04-19    14                   VRT 1
96  2025-04-19 20:25:04  2025-04-19    20                    VTM2
97  2025-04-19 23:12:47  2025-04-19    23                   PLAY4
98  2025-04-19 13:34:10  2025-04-19    13                   VRT 1
99  2025-04-19 18:21:12  2025-04-19    18                     VTM
100 2025-04-20 19:59:55  2025-04-20    19                   PLAY4
101 2025-04-20 20:04:57  2025-04-20    20                   VRT 1
102 2025-04-20 14:37:55  2025-04-20    14                   VRT 1
103 2025-04-20 19:58:22  2025-04-20    19                     VTM
104 2025-04-20 19:00:05  2025-04-20    19                   VRT 1
105 2025-04-20 19:22:09  2025-04-20    19                   VRT 1
106 2025-04-20 20:49:04  2025-04-20    20                   VRT 1
107 2025-04-20 13:33:44  2025-04-20    13                   VRT 1
108 2025-04-20 18:59:48  2025-04-20    18                     VTM
109 2025-04-20 21:18:46  2025-04-20    21                   PLAY4
110 2025-04-20 13:00:05  2025-04-20    13                   VRT 1
111 2025-04-20 21:40:14  2025-04-20    21                   VRT 1
112 2025-04-20 22:12:36  2025-04-20    22                   PLAY4
113 2025-04-20 17:33:25  2025-04-20    17                   VRT 1
114 2025-04-20 18:11:35  2025-04-20    18                   VRT 1
115 2025-04-20 18:29:07  2025-04-20    18              VRT CANVAS
116 2025-04-20 22:23:28  2025-04-20    22                   VRT 1
117 2025-04-20 12:59:48  2025-04-20    12                     VTM
118 2025-04-20 22:35:20  2025-04-20    22                     VTM
119 2025-04-20 21:15:41  2025-04-20    21                   PLAY5
120 2025-04-21 20:25:03  2025-04-21    20                   VRT 1
121 2025-04-21 19:00:04  2025-04-21    19                   VRT 1
122 2025-04-21 21:21:15  2025-04-21    21                   PLAY4
123 2025-04-21 19:47:19  2025-04-21    19                   VRT 1
124 2025-04-21 20:11:13  2025-04-21    20                     VTM
125 2025-04-21 18:59:43  2025-04-21    18                     VTM
126 2025-04-21 18:28:35  2025-04-21    18                   VRT 1
127 2025-04-21 13:00:05  2025-04-21    13                   VRT 1
128 2025-04-21 20:53:31  2025-04-21    20                   VRT 1
129 2025-04-21 20:46:08  2025-04-21    20                     VTM
130 2025-04-21 21:41:23  2025-04-21    21                   VRT 1
131 2025-04-21 12:59:38  2025-04-21    12                     VTM
132 2025-04-21 18:10:37  2025-04-21    18                   VRT 1
133 2025-04-21 18:24:43  2025-04-21    18                     VTM
134 2025-04-21 22:30:10  2025-04-21    22                   PLAY4
135 2025-04-21 19:59:02  2025-04-21    19                   PLAY4
136 2025-04-21 20:32:38  2025-04-21    20              VRT CANVAS
137 2025-04-21 21:53:05  2025-04-21    21                     VTM
138 2025-04-21 22:24:15  2025-04-21    22                   VRT 1
139 2025-04-21 21:21:56  2025-04-21    21              VRT CANVAS
140 2025-04-22 20:14:38  2025-04-22    20                   VRT 1
141 2025-04-22 19:00:04  2025-04-22    19                   VRT 1
142 2025-04-22 20:40:04  2025-04-22    20                   VRT 1
143 2025-04-22 20:44:32  2025-04-22    20                     VTM
144 2025-04-22 19:47:18  2025-04-22    19                   VRT 1
145 2025-04-22 20:08:07  2025-04-22    20                     VTM
146 2025-04-22 18:59:48  2025-04-22    18                     VTM
147 2025-04-22 18:28:25  2025-04-22    18                   VRT 1
148 2025-04-22 21:18:45  2025-04-22    21                   PLAY4
149 2025-04-22 21:25:25  2025-04-22    21                   VRT 1
150 2025-04-22 13:00:04  2025-04-22    13                   VRT 1
151 2025-04-22 22:12:56  2025-04-22    22                   VRT 1
152 2025-04-22 18:25:09  2025-04-22    18                     VTM
153 2025-04-22 20:37:49  2025-04-22    20              VRT CANVAS
154 2025-04-22 18:08:37  2025-04-22    18                   VRT 1
155 2025-04-22 19:59:02  2025-04-22    19                   PLAY4
156 2025-04-22 20:00:03  2025-04-22    20              VRT CANVAS
157 2025-04-22 22:12:02  2025-04-22    22                   PLAY4
158 2025-04-22 22:32:22  2025-04-22    22              VRT CANVAS
159 2025-04-22 21:29:24  2025-04-22    21              VRT CANVAS
160 2025-04-23 20:15:50  2025-04-23    20                   VRT 1
161 2025-04-23 19:00:04  2025-04-23    19                   VRT 1
162 2025-04-23 19:47:04  2025-04-23    19                   VRT 1
163 2025-04-23 20:08:51  2025-04-23    20                     VTM
164 2025-04-23 20:40:09  2025-04-23    20                   VRT 1
165 2025-04-23 18:59:48  2025-04-23    18                     VTM
166 2025-04-23 18:28:34  2025-04-23    18                   VRT 1
167 2025-04-23 20:43:34  2025-04-23    20                     VTM
168 2025-04-23 21:23:00  2025-04-23    21                   PLAY4
169 2025-04-23 13:45:21  2025-04-23    13                   VRT 1
170 2025-04-23 21:20:31  2025-04-23    21                   VRT 1
171 2025-04-23 16:59:18  2025-04-23    16                   VRT 1
172 2025-04-23 13:00:05  2025-04-23    13                   VRT 1
173 2025-04-23 18:10:25  2025-04-23    18                   VRT 1
174 2025-04-23 19:59:03  2025-04-23    19                   PLAY4
175 2025-04-23 21:54:53  2025-04-23    21                   VRT 1
176 2025-04-23 21:34:19  2025-04-23    21              VRT CANVAS
177 2025-04-23 12:59:48  2025-04-23    12                     VTM
178 2025-04-23 18:25:32  2025-04-23    18                     VTM
179 2025-04-23 22:33:01  2025-04-23    22                   PLAY4
180 2025-04-24 20:19:05  2025-04-24    20                   VRT 1
181 2025-04-24 19:00:04  2025-04-24    19                   VRT 1
182 2025-04-24 20:43:45  2025-04-24    20                     VTM
183 2025-04-24 19:50:28  2025-04-24    19                   VRT 1
184 2025-04-24 20:08:16  2025-04-24    20                     VTM
185 2025-04-24 18:59:48  2025-04-24    18                     VTM
186 2025-04-24 18:29:22  2025-04-24    18                   VRT 1
187 2025-04-24 13:00:04  2025-04-24    13                   VRT 1
188 2025-04-24 21:15:20  2025-04-24    21                   PLAY4
189 2025-04-24 20:44:36  2025-04-24    20                   VRT 1
190 2025-04-24 21:27:23  2025-04-24    21                    VTM2
191 2025-04-24 18:24:49  2025-04-24    18                     VTM
192 2025-04-24 21:56:28  2025-04-24    21                     VTM
193 2025-04-24 21:34:53  2025-04-24    21                   VRT 1
194 2025-04-24 18:09:41  2025-04-24    18                   VRT 1
195 2025-04-24 22:18:09  2025-04-24    22                   VRT 1
196 2025-04-24 21:25:04  2025-04-24    21              VRT CANVAS
197 2025-04-24 19:59:02  2025-04-24    19                   PLAY4
198 2025-04-24 20:37:02  2025-04-24    20              VRT CANVAS
199 2025-04-24 20:00:03  2025-04-24    20              VRT CANVAS
200 2025-04-25 20:15:52  2025-04-25    20                   VRT 1
201 2025-04-25 19:00:04  2025-04-25    19                   VRT 1
202 2025-04-25 19:46:44  2025-04-25    19                   VRT 1
203 2025-04-25 20:05:40  2025-04-25    20                     VTM
204 2025-04-25 20:40:32  2025-04-25    20                     VTM
205 2025-04-25 20:40:57  2025-04-25    20                   VRT 1
206 2025-04-25 18:59:48  2025-04-25    18                     VTM
207 2025-04-25 18:28:54  2025-04-25    18                   VRT 1
208 2025-04-25 13:00:04  2025-04-25    13                   VRT 1
209 2025-04-25 21:30:21  2025-04-25    21              VRT CANVAS
210 2025-04-25 22:28:10  2025-04-25    22                     VTM
211 2025-04-25 12:59:48  2025-04-25    12                     VTM
212 2025-04-25 18:10:55  2025-04-25    18                   VRT 1
213 2025-04-25 20:40:03  2025-04-25    20                   PLAY4
214 2025-04-25 20:37:35  2025-04-25    20              VRT CANVAS
215 2025-04-25 22:14:33  2025-04-25    22                   VRT 1
216 2025-04-25 21:31:36  2025-04-25    21                   VRT 1
217 2025-04-25 20:00:03  2025-04-25    20              VRT CANVAS
218 2025-04-25 14:40:26  2025-04-25    14                   VRT 1
219 2025-04-25 20:37:03  2025-04-25    20                    VTM2
220 2025-04-26 19:00:05  2025-04-26    19                   VRT 1
221 2025-04-26 20:56:20  2025-04-26    20                   VRT 1
222 2025-04-26 20:21:49  2025-04-26    20                   VRT 1
223 2025-04-26 18:59:49  2025-04-26    18                     VTM
224 2025-04-26 13:00:05  2025-04-26    13                   VRT 1
225 2025-04-26 19:52:28  2025-04-26    19                   VRT 1
226 2025-04-26 21:27:24  2025-04-26    21                   VRT 1
227 2025-04-26 19:58:23  2025-04-26    19                     VTM
228 2025-04-26 21:23:10  2025-04-26    21              VRT CANVAS
229 2025-04-26 22:25:38  2025-04-26    22                   VRT 1
230 2025-04-26 13:16:02  2025-04-26    13                     VTM
231 2025-04-26 20:30:03  2025-04-26    20                   PLAY4
232 2025-04-26 20:35:11  2025-04-26    20                     VTM
233 2025-04-26 09:00:04  2025-04-26     9                   VRT 1
234 2025-04-26 22:47:28  2025-04-26    22                   PLAY4
235 2025-04-26 13:29:52  2025-04-26    13                   VRT 1
236 2025-04-26 18:11:20  2025-04-26    18                   VRT 1
237 2025-04-26 08:30:03  2025-04-26     8                     VTM
238 2025-04-26 15:06:16  2025-04-26    15                   VRT 1
239 2025-04-26 20:25:04  2025-04-26    20                    VTM2
240 2025-04-27 20:00:24  2025-04-27    20                   PLAY4
241 2025-04-27 20:08:09  2025-04-27    20                   VRT 1
242 2025-04-27 19:00:04  2025-04-27    19                   VRT 1
243 2025-04-27 19:57:21  2025-04-27    19                     VTM
244 2025-04-27 19:19:59  2025-04-27    19                   VRT 1
245 2025-04-27 20:52:59  2025-04-27    20                   VRT 1
246 2025-04-27 18:59:40  2025-04-27    18                     VTM
247 2025-04-27 16:57:53  2025-04-27    16                   VRT 1
248 2025-04-27 13:34:56  2025-04-27    13                   VRT 1
249 2025-04-27 13:00:04  2025-04-27    13                   VRT 1
250 2025-04-27 21:17:45  2025-04-27    21                   PLAY4
251 2025-04-27 11:00:08  2025-04-27    11                   VRT 1
252 2025-04-27 22:24:30  2025-04-27    22                     VTM
253 2025-04-27 12:59:48  2025-04-27    12                     VTM
254 2025-04-27 21:46:21  2025-04-27    21                   VRT 1
255 2025-04-27 18:28:45  2025-04-27    18              VRT CANVAS
256 2025-04-27 22:13:26  2025-04-27    22                   PLAY4
257 2025-04-27 22:07:43  2025-04-27    22                   PLAY5
258 2025-04-27 18:26:13  2025-04-27    18  DAZN PRO LEAGUE 1 (NL)
259 2025-04-27 18:20:29  2025-04-27    18                     VTM
260 2025-04-28 19:00:04  2025-04-28    19                   VRT 1
261 2025-04-28 20:15:41  2025-04-28    20                   VRT 1
262 2025-04-28 21:14:47  2025-04-28    21                   PLAY4
263 2025-04-28 19:47:04  2025-04-28    19                   VRT 1
264 2025-04-28 20:09:28  2025-04-28    20                     VTM
265 2025-04-28 18:59:48  2025-04-28    18                     VTM
266 2025-04-28 18:29:37  2025-04-28    18                   VRT 1
267 2025-04-28 20:42:51  2025-04-28    20                   VRT 1
268 2025-04-28 21:30:29  2025-04-28    21                   VRT 1
269 2025-04-28 20:44:30  2025-04-28    20                     VTM
270 2025-04-28 13:00:05  2025-04-28    13                   VRT 1
271 2025-04-28 21:57:41  2025-04-28    21                     VTM
272 2025-04-28 19:59:03  2025-04-28    19                   PLAY4
273 2025-04-28 20:36:48  2025-04-28    20              VRT CANVAS
274 2025-04-28 22:25:29  2025-04-28    22                   PLAY4
275 2025-04-28 18:11:57  2025-04-28    18                   VRT 1
276 2025-04-28 18:25:35  2025-04-28    18                     VTM
277 2025-04-28 22:16:27  2025-04-28    22                   VRT 1
278 2025-04-28 20:00:03  2025-04-28    20              VRT CANVAS
279 2025-04-28 12:59:48  2025-04-28    12                     VTM
280 2025-04-29 20:16:14  2025-04-29    20                   VRT 1
281 2025-04-29 19:00:04  2025-04-29    19                   VRT 1
282 2025-04-29 20:40:19  2025-04-29    20                   VRT 1
283 2025-04-29 19:49:03  2025-04-29    19                   VRT 1
284 2025-04-29 20:39:30  2025-04-29    20                     VTM
285 2025-04-29 20:04:41  2025-04-29    20                     VTM
286 2025-04-29 18:59:45  2025-04-29    18                     VTM
287 2025-04-29 18:27:23  2025-04-29    18                   VRT 1
288 2025-04-29 13:00:05  2025-04-29    13                   VRT 1
289 2025-04-29 21:27:02  2025-04-29    21                   VRT 1
290 2025-04-29 21:19:16  2025-04-29    21                   PLAY4
291 2025-04-29 22:13:35  2025-04-29    22                   VRT 1
292 2025-04-29 21:01:57  2025-04-29    21                    VTM2
293 2025-04-29 21:51:46  2025-04-29    21                     VTM
294 2025-04-29 18:25:28  2025-04-29    18                     VTM
295 2025-04-29 18:10:34  2025-04-29    18                   VRT 1
296 2025-04-29 20:36:42  2025-04-29    20              VRT CANVAS
297 2025-04-29 20:00:03  2025-04-29    20              VRT CANVAS
298 2025-04-29 19:59:03  2025-04-29    19                   PLAY4
299 2025-04-29 12:59:48  2025-04-29    12                     VTM
300 2025-04-30 20:21:12  2025-04-30    20                   VRT 1

In [59]:
teVoorspellenData = pd.merge(teVoorspellenClean, histWeerdataClean, on=['date', 'hour', 'minute'], how='left')
teVoorspellenData = teVoorspellenData.drop(columns=['datetime', 'minute'])
print(teVoorspellenData)

             FullDate        date  hour Kanaal            Programma  \
0 2025-05-06 20:17:52  2025-05-06    20  VRT 1                THUIS
1 2025-05-06 19:00:04  2025-05-06    19  VRT 1   HET 7 UUR-JOURNAAL
2 2025-05-06 19:46:05  2025-05-06    19  VRT 1        MAN BIJT HOND
3 2025-05-06 18:29:07  2025-05-06    18  VRT 1              BLOKKEN
4 2025-05-06 18:59:48  2025-05-06    18    VTM       NIEUWS 19U VTM
5 2025-05-06 21:37:08  2025-05-06    21  VRT 1   DE DAG VAN VANDAAG
6 2025-05-06 20:05:28  2025-05-06    20    VTM              FAMILIE
7 2025-05-06 20:41:26  2025-05-06    20    VTM         HUIS GEMAAKT
8 2025-05-06 20:44:02  2025-05-06    20  VRT 1  GELUKKIG GESCHEIDEN
9 2025-05-06 13:00:04  2025-05-06    13  VRT 1   HET 1 UUR-JOURNAAL

   Lengte_sec Kijkers  Temperatuur  Gevoelstemp  Regen  Sneeuw  Weercode  \
0        1470    None         12.6          9.1    0.0     0.0         3
1        2598    None         13.0          9.3    0.0     0.0         3
2        1410    None         13.0          9.3    0.0     0.0         3
3        1710    None         13.8         10.0    0.1     0.0        51
4        3201    None         13.8         10.0    0.1     0.0        51
5        3206    None         11.9          8.5    0.0     0.0         3
6        1544    None         12.6          9.1    0.0     0.0         3
7        3945    None         12.6          9.1    0.0     0.0         3
8        3035    None         12.6          9.1    0.0     0.0         3
9        1653    None         14.4         10.2    0.0     0.0         0

   Bewolking  Windsnelheid  Zonnenschijn
0        100          18.0           0.0
1        100          18.8           0.0
2        100          18.8           0.0
3        100          17.3           0.0
4        100          17.3           0.0
5        100          17.2           0.0
6        100          18.0           0.0
7        100          18.0           0.0
8        100          18.0           0.0
9         11          15.3        3600.0

In [61]:
def tijdFeatures(df):
    df['date'] = pd.to_datetime(df['date'])
    #feestdagen
    feestdagen = holidays.BE()
    df['isFeestdag'] = df['date'].apply(lambda x: 1 if x in feestdagen else 0)
    #dag van de week
    df['Weekdag'] = df['date'].dt.weekday
    #weekend
    df['isWeekend'] = df['Weekdag'].apply(lambda x: 1 if x >= 5 else 0)
    #seizoenen
    df['Seizoen'] = df['date'].apply(seizoenFinder)

    return df

#seizoen
def seizoenFinder(datum):
    inputDatum = datum.date()
    Y = inputDatum.year
    seizoenen = {
        'lente': (date(Y, 3, 20), date(Y, 6, 20)),
        'zomer': (date(Y, 6, 21), date(Y, 9, 22)),
        'herfst':   (date(Y, 9, 23), date(Y, 12, 20)),
        'winter': (date(Y, 12, 21), date(Y + 1, 3, 19)),
    }

    for seizoen, (start, end) in seizoenen.items():
        if start <= inputDatum <= end:
            return seizoen
    return 'winter'

In [63]:
teVoorspellenData = tijdFeatures(teVoorspellenData)
histKijkcijfersWeer = tijdFeatures(histKijkcijfersWeer)
histWeerdataClean = tijdFeatures(histWeerdataClean)
histWeerdataClean.drop(columns=['minute'], inplace=True)
display(teVoorspellenData.head())
display(histKijkcijfersWeer.head())
display(histWeerdataClean.head())

,FullDate,date,hour,Kanaal,Programma,Lengte_sec,Kijkers,Temperatuur,Gevoelstemp,Regen,Sneeuw,Weercode,Bewolking,Windsnelheid,Zonnenschijn,isFeestdag,Weekdag,isWeekend,Seizoen
0,2025-05-06 20:17:52,2025-05-06,20,VRT 1,THUIS,1470,None,12.6,9.1,0.0,0.0,3,100,18.0,0.0,0,1,0,lente
1,2025-05-06 19:00:04,2025-05-06,19,VRT 1,HET 7 UUR-JOURNAAL,2598,None,13.0,9.3,0.0,0.0,3,100,18.8,0.0,0,1,0,lente
2,2025-05-06 19:46:05,2025-05-06,19,VRT 1,MAN BIJT HOND,1410,None,13.0,9.3,0.0,0.0,3,100,18.8,0.0,0,1,0,lente
3,2025-05-06 18:29:07,2025-05-06,18,VRT 1,BLOKKEN,1710,None,13.8,10.0,0.1,0.0,51,100,17.3,0.0,0,1,0,lente
4,2025-05-06 18:59:48,2025-05-06,18,VTM,NIEUWS 19U VTM,3201,None,13.8,10.0,0.1,0.0,51,100,17.3,0.0,0,1,0,lente

,FullDate,date,hour,Kanaal,Programma,Lengte_sec,Kijkers,Temperatuur,Gevoelstemp,Regen,Sneeuw,Weercode,Bewolking,Windsnelheid,Zonnenschijn,isFeestdag,Weekdag,isWeekend,Seizoen
0,2025-04-15 20:14:58,2025-04-15,20,VRT 1,THUIS,1469,988011,16.6,14.5,0.0,0.0,3,98,13.6,3600.0,0,1,0,lente
1,2025-04-15 20:41:25,2025-04-15,20,VRT 1,FACTCHECKERS,2654,889262,16.6,14.5,0.0,0.0,3,98,13.6,3600.0,0,1,0,lente
2,2025-04-15 19:00:05,2025-04-15,19,VRT 1,HET 7 UUR-JOURNAAL,2501,810136,18.0,16.2,0.0,0.0,3,90,11.1,3600.0,0,1,0,lente
3,2025-04-15 21:27:50,2025-04-15,21,VRT 1,KNOKKE OFF,1895,750554,14.9,13.0,0.0,0.0,2,63,12.3,0.0,0,1,0,lente
4,2025-04-15 20:44:56,2025-04-15,20,VTM,HUIS GEMAAKT,3346,609911,16.6,14.5,0.0,0.0,3,98,13.6,3600.0,0,1,0,lente

,datetime,date,hour,Temperatuur,Gevoelstemp,Regen,Sneeuw,Weercode,Bewolking,Windsnelheid,Zonnenschijn,isFeestdag,Weekdag,isWeekend,Seizoen
0,2025-04-15 00:00:00,2025-04-15,0,12.3,10.0,0.0,0.0,3,81,9.8,0.0,0,1,0,lente
1,2025-04-15 01:00:00,2025-04-15,1,11.6,9.4,0.0,0.0,1,44,9.5,0.0,0,1,0,lente
2,2025-04-15 02:00:00,2025-04-15,2,11.1,8.8,0.0,0.0,1,32,10.1,0.0,0,1,0,lente
3,2025-04-15 03:00:00,2025-04-15,3,10.8,8.1,0.0,0.0,3,90,11.6,0.0,0,1,0,lente
4,2025-04-15 04:00:00,2025-04-15,4,10.7,8.1,0.0,0.0,3,98,11.8,0.0,0,1,0,lente

In [121]:
def lagFeatures(df, hist):
  df['Kijkers'] = None
  df = pd.concat([hist, df], ignore_index=True)
  # Sorteer op tijd binnen elke groep
  df = df.sort_values(['Programma', 'FullDate'])

  df = df.sort_values(['Programma', 'FullDate'])

  # Bereken gemiddelde kijkers per Programma (op basis van historische data)
  kijkers_mean = df.groupby('Programma')['Kijkers'].transform('mean')

  # Bereken lag features per programma
  for i in range(1, 4):
      df[f'Kijkers_lag_{i}'] = df.groupby('Programma')['Kijkers'].shift(i)
      df[f'Kijkers_lag_{i}'] = df[f'Kijkers_lag_{i}'].fillna(kijkers_mean).round().astype(int)

  return df

In [122]:
pred_hist_df = lagFeatures(teVoorspellenData, histKijkcijfersWeer)
print("lagfeatures toegevoegd: ")
display(pred_hist_df.dtypes)
display(pred_hist_df.sort_values(by='FullDate').tail(10))
display(pred_hist_df[pred_hist_df.isna().any(axis=1)])

C:\Users\krist\AppData\Local\Temp\ipykernel_10392\1906661763.py:15: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[f'Kijkers_lag_{i}'] = df[f'Kijkers_lag_{i}'].fillna(kijkers_mean).round().astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [14]:
def oneHot(df):
  with open('./models/oneHotEncoder.pkl', 'rb') as oneHotFile:
    oneHotEnc = pickle.load(oneHotFile)

  lageKard = df[[ 'hour','Kanaal', 'isFeestdag', 'Weekdag', 'Seizoen']]
  dfOneHot = oneHotEnc.transform(lageKard)

  oneHotOutp = pd.DataFrame(dfOneHot.toarray(), 
                            columns=oneHotEnc.get_feature_names_out(), 
                            index=lageKard.index)

  df = df.drop(columns=['hour', 'Kanaal', 'isFeestdag', 'Weekdag', 'Seizoen'])
  df = pd.concat([df, oneHotOutp], axis = 1)
  return df

def target(df):
  #target encoding voor medium kardinaliteiten
  with open('./models/oneHotTarget.pkl', 'rb') as f:
    targetEnc = pickle.load(f)
  medKardinaliteit = df[['date', 'Programma', 'Lengte_sec', 'Temperatuur', 'Gevoelstemp', 'Regen', 'Bewolking', 'Windsnelheid', 'Zonnenschijn']]
  #verdere feature engineering op vorig model
  target = targetEnc.transform(medKardinaliteit)
  df = df.drop(columns=['date', 'Programma', 'Lengte_sec', 'Temperatuur', 'Gevoelstemp', 'Regen', 'Bewolking', 'Windsnelheid', 'Zonnenschijn'])
  f = pd.concat([df, target], axis=1)

  return f

In [35]:
teVoorspellenData = oneHot(pred_hist_df)
print("onehotencoding: ")
display(teVoorspellenData.head())
# Target encoding
targetOneHotEnc = target(teVoorspellenData)
print("targetencoding: ")
display(targetOneHotEnc.head())

onehotencoding:

,FullDate,date,Programma,Lengte_sec,Kijkers,Temperatuur,Gevoelstemp,Regen,Sneeuw,Weercode,Bewolking,Windsnelheid,Zonnenschijn,isWeekend,Kijkers_lag_1,Kijkers_lag_2,Kijkers_lag_3,hour_0,hour_1,hour_2,hour_6,hour_7,hour_8,hour_9,hour_10,hour_11,hour_12,hour_13,hour_14,hour_15,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23,Kanaal_AB3,Kanaal_CANVAS,Kanaal_CAZ,Kanaal_Canvas,Kanaal_DAZN_PRO_LEAGUE_1_(NL),Kanaal_EEN,Kanaal_ELEVEN_PRO_LEAGUE_1_NL,Kanaal_EUROSPORT_1_(NL),Kanaal_KETNET,Kanaal_LA_UNE,Kanaal_OP_12,Kanaal_PLAY4,Kanaal_PLAY5,Kanaal_PLAY6,Kanaal_PLAY_SPORTS_OPEN,Kanaal_Q2,Kanaal_RTL-TVI,Kanaal_TF1,Kanaal_VIER,Kanaal_VIJF,Kanaal_VITAYA,Kanaal_VRT_1,Kanaal_VRT_CANVAS,Kanaal_VTM,Kanaal_VTM2,Kanaal_VTM3,Kanaal_VTM4,Kanaal_VTM_GOLD,Kanaal_ZES,isFeestdag_0,isFeestdag_1,Weekdag_0,Weekdag_1,Weekdag_2,Weekdag_3,Weekdag_4,Weekdag_5,Weekdag_6,Seizoen_herfst,Seizoen_lente,Seizoen_winter,Seizoen_zomer
193,2025-04-24 21:34:53,2025-04-24,112 HULP IS ONDERWEG,2394,267015,10.6,8.4,0.0,0.0,3,100,13.0,0.0,0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
331,2025-05-01 21:20:48,2025-05-01,112 HULP IS ONDERWEG,2704,284605,24.9,23.3,0.0,0.0,3,100,6.9,0.0,0,267015,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
72,2025-04-18 22:11:57,2025-04-18,9-1-1,2467,255485,12.0,9.0,0.0,0.0,3,100,10.8,0.0,0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
210,2025-04-25 22:28:10,2025-04-25,9-1-1,2437,275338,10.7,8.9,0.0,0.0,0,3,9.6,0.0,0,255485,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
352,2025-05-02 22:40:33,2025-05-02,9-1-1,2427,209967,17.0,15.4,0.0,0.0,1,27,11.7,0.0,0,275338,255485,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0

targetencoding:

,FullDate,Kijkers,Sneeuw,Weercode,isWeekend,Kijkers_lag_1,Kijkers_lag_2,Kijkers_lag_3,hour_0,hour_1,hour_2,hour_6,hour_7,hour_8,hour_9,hour_10,hour_11,hour_12,hour_13,hour_14,hour_15,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23,Kanaal_AB3,Kanaal_CANVAS,Kanaal_CAZ,Kanaal_Canvas,Kanaal_DAZN_PRO_LEAGUE_1_(NL),Kanaal_EEN,Kanaal_ELEVEN_PRO_LEAGUE_1_NL,Kanaal_EUROSPORT_1_(NL),Kanaal_KETNET,Kanaal_LA_UNE,Kanaal_OP_12,Kanaal_PLAY4,Kanaal_PLAY5,Kanaal_PLAY6,Kanaal_PLAY_SPORTS_OPEN,Kanaal_Q2,Kanaal_RTL-TVI,Kanaal_TF1,Kanaal_VIER,Kanaal_VIJF,Kanaal_VITAYA,Kanaal_VRT_1,Kanaal_VRT_CANVAS,Kanaal_VTM,Kanaal_VTM2,Kanaal_VTM3,Kanaal_VTM4,Kanaal_VTM_GOLD,Kanaal_ZES,isFeestdag_0,isFeestdag_1,Weekdag_0,Weekdag_1,Weekdag_2,Weekdag_3,Weekdag_4,Weekdag_5,Weekdag_6,Seizoen_herfst,Seizoen_lente,Seizoen_winter,Seizoen_zomer,date,Programma,Lengte_sec,Temperatuur,Gevoelstemp,Regen,Bewolking,Windsnelheid,Zonnenschijn
193,2025-04-24 21:34:53,267015,0.0,3,0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2206.432619,1664.888486,2394,10.6,8.4,0.0,100,13.0,0.0
331,2025-05-01 21:20:48,284605,0.0,3,0,267015,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2206.432619,1664.888486,2704,24.9,23.3,0.0,100,6.9,0.0
72,2025-04-18 22:11:57,255485,0.0,3,0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,2206.432619,107.094066,2467,12.0,9.0,0.0,100,10.8,0.0
210,2025-04-25 22:28:10,275338,0.0,0,0,255485,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,2206.432619,107.094066,2437,10.7,8.9,0.0,3,9.6,0.0
352,2025-05-02 22:40:33,209967,0.0,1,0,275338,255485,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,2206.432619,107.094066,2427,17.0,15.4,0.0,27,11.7,0.0

In [37]:
teVoorspellenData = targetOneHotEnc.select_dtypes(include=[np.number])
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
teVoorspellenData.dtypes

Sneeuw                           float64
Weercode                           int64
isWeekend                          int64
hour_0                           float64
hour_1                           float64
hour_2                           float64
hour_6                           float64
hour_7                           float64
hour_8                           float64
hour_9                           float64
hour_10                          float64
hour_11                          float64
hour_12                          float64
hour_13                          float64
hour_14                          float64
hour_15                          float64
hour_16                          float64
hour_17                          float64
hour_18                          float64
hour_19                          float64
hour_20                          float64
hour_21                          float64
hour_22                          float64
hour_23                          float64
Kanaal_AB3                       float64
Kanaal_CANVAS                    float64
Kanaal_CAZ                       float64
Kanaal_Canvas                    float64
Kanaal_DAZN_PRO_LEAGUE_1_(NL)    float64
Kanaal_EEN                       float64
Kanaal_ELEVEN_PRO_LEAGUE_1_NL    float64
Kanaal_EUROSPORT_1_(NL)          float64
Kanaal_KETNET                    float64
Kanaal_LA_UNE                    float64
Kanaal_OP_12                     float64
Kanaal_PLAY4                     float64
Kanaal_PLAY5                     float64
Kanaal_PLAY6                     float64
Kanaal_PLAY_SPORTS_OPEN          float64
Kanaal_Q2                        float64
Kanaal_RTL-TVI                   float64
Kanaal_TF1                       float64
Kanaal_VIER                      float64
Kanaal_VIJF                      float64
Kanaal_VITAYA                    float64
Kanaal_VRT_1                     float64
Kanaal_VRT_CANVAS                float64
Kanaal_VTM                       float64
Kanaal_VTM2                      float64
Kanaal_VTM3                      float64
Kanaal_VTM4                      float64
Kanaal_VTM_GOLD                  float64
Kanaal_ZES                       float64
isFeestdag_0                     float64
isFeestdag_1                     float64
Weekdag_0                        float64
Weekdag_1                        float64
Weekdag_2                        float64
Weekdag_3                        float64
Weekdag_4                        float64
Weekdag_5                        float64
Weekdag_6                        float64
Seizoen_herfst                   float64
Seizoen_lente                    float64
Seizoen_winter                   float64
Seizoen_zomer                    float64
date                             float64
Programma                        float64
Lengte_sec                         int64
Temperatuur                      float64
Gevoelstemp                      float64
Regen                            float64
Bewolking                          int64
Windsnelheid                     float64
Zonnenschijn                     float64
dtype: object

In [38]:
try:
    with open('./models/optunaBestModel.pkl', 'rb') as file:
        lgbm = pickle.load(file)
except Exception as e:
    print("Kon model niet laden:", e)
    exit(1)

predictions = lgbm.predict(teVoorspellenData)
display(predictions)

LightGBMError: The number of features in data (75) is not the same as it was in training data (78).
You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.